appname: e-book-Gin

db:
  name:     datashare
  user:     root
  password: 123456
  port:     3310
#  k8s不行
#  host: 10.4.103.132

# k8s和docker都行
  host: localhost

# k8s 和 docker 中都不行
#  host: 127.0.0.1
#  host: 172.18.176.1

# k8s 不行
#  host: 172.17.0.1

contacts:
  - name: i test
    email: test@test.com