apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-book-gin
  labels:
    app: e-book-gin
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-book-gin
      version: v1.0.0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: e-book-gin
        version: v1.0.0
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/hfut-ie/e-book-gin:v3.0 #镜像
          name: e-book-gin
          ports:
            - containerPort: 7777
              name: e-book-gin
