apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-book-gin
  labels:
    app: e-book-gin
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-book-gin
      version: v1.0.0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: e-book-gin
        version: v1.0.0
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/hfut-ie/ebook:v5.0 #镜像
          name: ebook
          ports:
            - containerPort: 6666
              name: e-book-gin
          env: 
            - name: MYSQL_ADDRESS
              valueFrom: 
                configMapKeyRef:
                  name: mysql-config
                  key: mysqlHost
