apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mysql
  labels:
    app: my-mysql
    version: v1.0.0
spec:
  selector:
    matchLabels:
      app: my-mysql
      version: v1.0.0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-mysql
        version: v1.0.0
    spec:
      containers:
        - image: mysql:latest
          name: my-mysql
          args:
#            - "--ignore-db-dir=lost+found"
            - "--character-set-server=utf8"     #  指定字符编码
            - "--collation-server=utf8_general_ci"    #  指定字符编码
          env:
            - name: MYSQL_ROOT_PASSWORD    #  指定root用户的用户名
              value: "123456"
#            - name: MYSQL_PASSWORD     #  新建用户的用户名
#              value: "123456"
#            - name: MYSQL_USER        # 新建的用户
#              value: "ljs"
            - name: MYSQL_DATABASE    # 新建的数据库
              value: "datashare"
          ports:
            - containerPort: 3310
              name: mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
              subPath: mysqld.cnf
              readOnly: False
      volumes:
        - name: data
#          persistentVolumeClaim:
#            claimName: mysql-pvc
        - name: config
#          configMap:
#            name: mysql-configmap