apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod
spec:
  #定义容器 可以多个
  containers:
    - name: test-pod #容器名字
      image: ccr.ccs.tencentyun.com/hfut-ie/e-book-gin:v3.0 #镜像
      ports:
        - containerPort: 7777
          name: test-pod
          hostPort: 7777
#  dnsPolicy: ClusterFirst
#  hostNetwork: true
